### ISSUE TITLE
Docs Make Build Failed. 

### ISSUE THREAD

**Issue by xinyu7git** [prometheus/docs#1229]
Captain! We’ve been hit!

  ... 8 lines omitted (see crash.log for details)
  9. from /Users/zoro/Documents/opensources/prometheus_doc/vendor/ruby/2.5.0/gems/nanoc-4.9.3/lib/nanoc/base/entities/action_sequence.rb:50:in `each'
  8. from /Users/zoro/Documents/opensources/prometheus_doc/vendor/ruby/2.5.0/gems/nanoc-4.9.3/lib/nanoc/base/entities/action_sequence.rb:50:in `each'
  7. from /Users/zoro/Documents/opensources/prometheus_doc/vendor/ruby/2.5.0/gems/nanoc-4.9.3/lib/nanoc/base/entities/action_sequence.rb:50:in `block in each'
  6. from /Users/zoro/Documents/opensources/prometheus_doc/vendor/ruby/2.5.0/gems/nanoc-4.9.3/lib/nanoc/base/services/compiler/phases/recalculate.rb:32:in `block in run'
  5. from /Users/zoro/Documents/opensources/prometheus_doc/vendor/ruby/2.5.0/gems/nanoc-4.9.3/lib/nanoc/base/services/executor.rb:65:in `layout'
  4. from /Users/zoro/Documents/opensources/prometheus_doc/vendor/ruby/2.5.0/gems/nanoc-4.9.3/lib/nanoc/base/services/filter.rb:157:in `setup_and_run'
  3. from /Users/zoro/Documents/opensources/prometheus_doc/vendor/ruby/2.5.0/gems/nanoc-4.9.3/lib/nanoc/filters/erb.rb:36:in `run'
  2. from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/erb.rb:876:in `result'
  1. from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/erb.rb:876:in `eval'
  layout /docs/:7:in `get_binding'

NoMethodError: undefined method `children' for nil:NilClass

Current item: /docs/alerting/notification_examples/ (:default representation)

A detailed crash log has been written to ./crash.log.
make: *** [compile] Error 1

**Comment by lucperkins** [comment]
@xinyu7git You appear to be using Ruby version 2.5.1. You'll need to use Ruby 2.4.3. Could you try with that version instead and see if the issue goes away?
