### ISSUE TITLE
Outdated download link on https://prometheus.io/download/#alertmanager

### ISSUE THREAD

**Issue by psliwka** [prometheus/docs#1510]
**What did you do?**
Opened https://prometheus.io/download/#alertmanager

**What did you expect to see?**
Download link and checksums of released Alertmanager 0.20.0

**What did you see instead? Under which circumstances?**
Releases 0.19.0 and 0.20.0-rc.0

**Comment by juliusv** [comment]
Hmm, the docs build on Netlify is failing with:

```
11:22:05 AM: bundle exec nanoc
11:22:06 AM: bundler: failed to load command: nanoc (/opt/build/cache/bundle/ruby/2.4.0/bin/nanoc)
11:22:06 AM: LoadError: /lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by /opt/buildhome/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/x86_64-linux/openssl.so) - /opt/buildhome/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/x86_64-linux/openssl.so
11:22:06 AM:   /opt/buildhome/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/openssl.rb:13:in `require'
11:22:06 AM:   /opt/buildhome/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/openssl.rb:13:in `<top (required)>'
11:22:06 AM:   /opt/buildhome/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/net/https.rb:23:in `require'
11:22:06 AM:   /opt/buildhome/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/net/https.rb:23:in `<top (required)>'
11:22:06 AM:   /opt/build/cache/bundle/ruby/2.4.0/gems/nanoc-4.11.0/lib/nanoc.rb:50:in `require'
11:22:06 AM:   /opt/build/cache/bundle/ruby/2.4.0/gems/nanoc-4.11.0/lib/nanoc.rb:50:in `<top (required)>'
11:22:06 AM:   /opt/build/cache/bundle/ruby/2.4.0/gems/nanoc-4.11.0/bin/nanoc:4:in `require'
11:22:06 AM:   /opt/build/cache/bundle/ruby/2.4.0/gems/nanoc-4.11.0/bin/nanoc:4:in `<top (required)>'
11:22:06 AM:   /opt/build/cache/bundle/ruby/2.4.0/bin/nanoc:23:in `load'
11:22:06 AM:   /opt/build/cache/bundle/ruby/2.4.0/bin/nanoc:23:in `<top (required)>'
11:22:06 AM: make: *** [compile] Error 1
```

Haven't found out yet why.

**Comment by juliusv** [comment]
I restarted the Netlify build with a clean cache, and now it built fine.
